api = "0.6"

[buildpack]
id = "sam/legacy-sbom-compat-buildpack"
version = "0.0.1"
name = "Label Descriptor"
desription = "Add legacy SBOMs to your project"
homepage = "https://github.com/samj1912/legacy-sbom-compat-buildpack"
keywords = ["compat", "sbom", "legacy"]

[[buildpack.licenses]]
type = "Apache 2.0"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
